import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Load dev config if exists
let vaultPluginPath = null;
try {
	const devConfig = JSON.parse(fs.readFileSync('.obsidian-dev.json', 'utf8'));
	vaultPluginPath = devConfig.vaultPluginPath;
} catch (e) {
	// Config file not found or invalid, skip copying
}

// Copy files to vault plugin folder
function copyToVault() {
	if (!vaultPluginPath) return;
	
	try {
		// Create directory if it doesn't exist
		if (!fs.existsSync(vaultPluginPath)) {
			fs.mkdirSync(vaultPluginPath, { recursive: true });
		}
		
		// Copy main.js
		fs.copyFileSync('main.js', path.join(vaultPluginPath, 'main.js'));
		
		// Copy manifest.json
		fs.copyFileSync('manifest.json', path.join(vaultPluginPath, 'manifest.json'));
		
		// Copy styles.css
		fs.copyFileSync('styles.css', path.join(vaultPluginPath, 'styles.css'));
		
		console.log(`✓ Files copied to ${vaultPluginPath}`);
	} catch (e) {
		console.error('Failed to copy files to vault:', e.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyToVault();
	process.exit(0);
} else {
	await context.watch();
}
